version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    branches:
      only:
        - master
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew test
      - store_test_results:
          path: webapp/build/test-results
      - run:
          name: Deploy to Heroku
          command: |
            git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/isolating-the-domain.git master
      - run: sudo apt-get update && sudo apt-get install -y graphviz fonts-ipafont
      - run: ./gradlew jig
      - store_artifacts:
          path: webapp/build/jig
          destination: example

